### PR TITLE
Some HTML experience

### PR DESCRIPTION
**Pull request by lucasprice**
Added new background and option for language :) .

### CODE REVIEW

**Review by nicolasbock — COMMENTED** [review]
This looks very promising @lucasprice :smile: Please rebase your PR to remove the merge conflicts? (@mprices let me know if you want me to help here. Rebasing is sometimes a little tricky :smile:)

**Comment by lucasprice** [comment]
OK. we tried to rebase and switch picture back.

**Review by adisbock — COMMENTED** [review]
what??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????........do you want to change?

**Review by nicolasbock — APPROVED** [review]
Thanks!

**Pull request merged**
